image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY: registry.gitlab.com
  PROJECT_GROUP: $CI_PROJECT_NAMESPACE
  PROJECT_NAME: $CI_PROJECT_NAME
  PACK_VERSION: $CI_COMMIT_REF_NAME
  GCP_PROJECT_ID: nexus-docker-204414

services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY

stages:
- build_ng_serve
- build_nginx_php_fpm
- publish

build_ng_serve:
  stage: build_ng_serve
  only:
    - branches
  script:
    - docker build -t $PROJECT_GROUP/nexus-ng-serve::$PACK_VERSION nexus-ng-serve/
    - docker run $PROJECT_GROUP/nexus-ng-serve npm --version

build_nginx_php_fpm:
  stage: build_nginx_php_fpm
  only:
    - branches
  script:
    - docker build -t $PROJECT_GROUP/nexus-nginx-php-fpm:$PACK_VERSION nexus-nginx-php-fpm/
    - docker run $PROJECT_GROUP/nexus-nginx-php-fpm npm --version

publish-image:
  stage: publish
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
    - docker push $REGISTRY/$PROJECT_GROUP/nexus-ng-serve:$PACK_VERSION
    - docker push $REGISTRY/$PROJECT_GROUP/nexus-nginx-php-fpm:$PACK_VERSION
