image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  REGISTRY: registry.gitlab.com
  PROJECT_GROUP: $CI_PROJECT_NAMESPACE
  PROJECT_NAME: $CI_PROJECT_NAME
  PACK_VERSION: $CI_COMMIT_REF_NAME
  GCP_PROJECT_ID: nexus-docker-204414

services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY

stages:
- build

build_ng_serve:
  stage: build
  only:
    - branches
  script:
    - docker build -t $REGISTRY/$PROJECT_GROUP/nexus-ng-serve:${CI_COMMIT_SHA:0:8} nexus-ng-serve/
    - docker run $REGISTRY/$PROJECT_GROUP/nexus-ng-serve:${CI_COMMIT_SHA:0:8} npm --version
    - docker push $REGISTRY/$PROJECT_GROUP/nexus-ng-serve

build_nginx_php_fpm:
  stage: build
  only:
    - branches
  script:
    - docker build -t $REGISTRY/$PROJECT_GROUP/nexus-nginx-php-fpm:${CI_COMMIT_SHA:0:8} nexus-nginx-php-fpm/
    - docker run --entrypoint "composer" $REGISTRY/$PROJECT_GROUP/nexus-nginx-php-fpm:${CI_COMMIT_SHA:0:8} --version
    - docker push $REGISTRY/$PROJECT_GROUP/nexus-nginx-php-fpm
