sudo: required
services:
- docker
language: bash
script:
# build image
- docker build -t mvcaaa/nexus-ng-serve nexus-ng-serve/
- docker build -t mvcaaa/nexus-nginx-php-fpm nexus-nginx-php-fpm/
# test image
- docker run mvcaaa/nexus-ng-serve npm --version
- docker run --entrypoint "composer" mvcaaa/nexus-nginx-php-fpm --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG1=$(grep "ENV IMAGE_VERSION" Dockerfile.ng-serve | awk 'NF>1{print $NF}')
    docker tag mvcaaa/nexus-ng-serve mvcaaa/nexus-ng-serve:$TAG1
    docker push mvcaaa/nexus-ng-serve:$TAG1
    docker push mvcaaa/nexus-ng-serve
    TAG2=$(grep "ENV IMAGE_VERSION" Dockerfile.nginx-php-fpm | awk 'NF>1{print $NF}')
    docker tag mvcaaa/nexus-nginx-php-fpm mvcaaa/nexus-nginx-php-fpm:$TAG2
    docker push mvcaaa/nexus-nginx-php-fpm:$TAG2
    docker push mvcaaa/nexus-nginx-php-fpm
  fi
# end
