version: '3.6'

services:
  nginx-php-fpm:
    image: "registry.gitlab.com/mvcaaa/nexus-docker/nginx-php-fpm"
    build:
      context: ./nexus-nginx-php-fpm/
      dockerfile: Dockerfile
    volumes:
      - ${NEXUS_HOME}:/var/www/installations/nexus
      - ${NEXUS_BOOT}:/var/www/boot
      - ${NEXUS_DOCKER_HOME}\files\nginx\certs:/opt/certs
      - ${NEXUS_DOCKER_HOME}\files\nginx-php-fpm-start.sh:/start.sh
      - ${NEXUS_DOCKER_HOME}\files\nginx:/etc/nginx
      # This is caches/composer vendor folder
      - php-vendor:/var/www/installations/nexus/lib/vendor
      - php-vendor-cache:/root/.composer
      - ng-serve-nodemodules:/var/www/installations/nexus/nexus_ng/node_modules
    environment:
        ENABLE_XDEBUG: ${IS_XDEBUG_ENABLED}
        PHP_XDEBUG_ENABLED: ${IS_XDEBUG_ENABLED}
        XDEBUG_CONFIG: ${XDEBUG_CONFIG}
        # WEBROOT: "/var/www/installations/nexus"
        APPLICATION_ENV: ${APPLICATION_ENV}
        COMPOSER_WORKING_DIR: /var/www/installations/nexus/lib
    ports:
      - 80:80
      - 443:443
    external_links:
      - dataservices_redis_1:redis
      - dataservices_mysql_1:mysql
    # links:
    #   - redis
    #   - mysql
    networks:
      - core-infra

networks:
  core-infra:
    external: true

volumes:
  php-vendor:
  php-vendor-cache:
  ng-serve-nodemodules:
  ng-build-dist:
