title = "nexus mvc dev docker"
version = "1.9.0.10"
timezone = "Europe/Helsinki"
storage = "local"
use_ng_live_reload = "true"
cache = "black_hole" 

[redis]
#host = "redis"
#port = "6379"

[aliases]

[database]
host = "dev"
username = "www"
password = "rofl-tosc-zekp-cexl-leyn-dokr"
#host = "10.0.75.1"
#username = "root"
#password = "SuperVGA256"
charset = "utf8"
environment = "nexus_base"

[replica_database]
host = "mysql"
username = "www"
password = ""
charset = "utf8"
