title = "nexus dev docker"
version = "1.9.0.10"
timezone = "Europe/Helsinki"
storage = "local"
use_ng_live_reload = "true"

[redis]
host = "redis"

[aliases]

[database]
host = "mysql"
username = "www"
password = ""
charset = "utf8"
environment = "dev"

[replica_database]
host = "mysql"
username = "www"
password = ""
charset = "utf8"
